encoding: utf-8


title: Flyg0n Blog
description: Flyg0n Blog
keywords: Flyg0n,Blog,C++,Cyber Security,Linux
author: Flyg0n
language: en
footerText: 'guess whah'

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

domainUrl: ''
baseurl: ''

menu:
  - title: home
    url: /
  - title: catagorize
    url: /pages/categories.html
  - title: search
    url: /pages/search.html
  - title: about
    url: /pages/about.html

extClickEffect: true


    

theme: jekyll-theme-minimal